name: Update XHS Trends

on:
  schedule:
    - cron: "0 1 * * 1-5" #工作日每天 09:00（KL）
  workflow_dispatch: {}

permissions:
  contents: write   # 允许推送到仓库

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (none required)
        run: python -c "print('OK')"

      - name: Run generator
        env:
          REGION_HINT: MY   # CN / MY / SG / GLOBAL
        run: |
          python scripts/update_trends.py

      - name: Commit & Push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add xhs_trends.json
          git diff --quiet && echo "No changes" || git commit -m "Auto-update trends: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push
